### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by cbiggles**

### CODE REVIEW

**Comment by cbiggles** [comment]
test

**Comment by cbiggles** [comment]
test 2

**Comment by cbiggles** [comment]
test

**Comment by cbiggles** [comment]
test

**Comment by cbiggles** [comment]
aa

**Comment by cbiggles** [comment]
a

**Comment by cbiggles** [comment]
test

**Comment by cbiggles** [comment]
test2

**Comment by cbiggles** [comment]
foo

**Comment by cbiggles** [comment]
again

**Comment by berkerpeksag** [comment]
backport to 3.6

**Comment by cbiggles** [comment]
9d9ed0e5cceef45fd63dc1f7b3fe6e695da16e83 has been cherry-picked into '3.5' as b'1e0c9b0a4663556d92af62f7f6502a2596240795\n'.

**Comment by cbiggles** [comment]
9d9ed0e5cceef45fd63dc1f7b3fe6e695da16e83 has been cherry-picked into '3.5' as 2d420b342509e6c2b597af82ea74c4cbb13e2abd.

**Pull request merged**
