### PR TITLE
Remove stray comment in setup.py

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by berkerpeksag** [comment]
backport to 3.5

**Comment by berkerpeksag** [comment]
backport to 3.5

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.5' as 2d420b342509e6c2b597af82ea74c4cbb13e2abd.

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.5' as .

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.5' as .

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.5' as 2d420b342509e6c2b597af82ea74c4cbb13e2abd.

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.5' as 5591dd65f1e742bf65a65c25741d6b9c38cf7203.

**Comment by berkerpeksag** [comment]
backport to 3.4

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.4' as 4faefc08b2c0eb1d3838eb0f7046e22c60296f3e.

**Comment by berkerpeksag** [comment]
backport to 3.3

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.3' as 5474673d73ab1bc7a5cdd9e7213e80b687e8f9da.

**Comment by berkerpeksag** [comment]
backport to 3.2

**Comment by cbiggles** [comment]
0fa66fd8b92f6bc5f68f8bc3f0b297c83aa41a0f has been cherry-picked into '3.2' as 801f6e44ec511999402d19cee84789f059e2bf52.

**Pull request merged**
